### ISSUE TITLE
How do we change intervals?

### ISSUE THREAD

**Issue by IlyaTataurov** [walmat/Off-White-Monitor#1]
Is there a way to change intervals?

**Comment by walmat** [comment]
Hey! Good question. I should've left a comment near that line, but here's the exact line. One thing to mention: the lower the delay, the more threads will be running at one time. 

https://github.com/walmat/Off-White-Monitor/blob/387faf676bf1fc7b2416ff7e9d687e5d48aeb3b9/ow.py#L325

**Comment by IlyaTataurov** [comment]
Sounds good, another question, if I want it to pick up every change, can I just leave keywords blank?

**Comment by walmat** [comment]
Yeah the keywords are only used if you want to look for specific products. It should work if you leave them blank and gather all the products. Reply to this issue if it doesn't though and I can take a look at it. 

cc @IlyaTataurov

**Comment by IlyaTataurov** [comment]
Sounds good, they work fine but the monitor just keeps picking up out of stock products 
![image](https://user-images.githubusercontent.com/38859788/41780329-096f3142-75fa-11e8-9397-08410b7b999d.png), do you know why that is?

**Comment by walmat** [comment]
This is on initialization of the monitor. It will initialize the database to all products, if they are found, to have something to compare to. If they find that either a) stock changes, or b) price changes, then it will notify the user and push the changes to the product database. 

That being said, I'm working on rewriting this entirely to incorporate an electron shell and be much more intuitive. Be on the lookout for that here within a week.

cc @IlyaTataurov

**Comment by Chasenlz** [comment]
cc @IlyaTataurov 
Did you code your dsm monitor or get code, if so please send it to me because I would like to have one, please and thank you
