### ISSUE TITLE
Import OW

### ISSUE THREAD

**Issue by Chasenlz** [walmat/Off-White-Monitor#3]
File "/Users/chaselazarian/Desktop/Off-White-Monitor-master/main.py", line 4, in <module>
    import ow
  File "/Users/chaselazarian/Desktop/Off-White-Monitor-master/ow.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
I fixed this but no products would show up, so I restarted but well, this is what I get

**Comment by walmat** [comment]
Sorry for the delay. Make sure you read the README thoroughly. 

To solve any dependency issues, run `pip install <module>` 

e.g. for your issue, run `pip install requests`

**Comment by Chasenlz** [comment]
I already pip installed request but I get the same error

**Comment by Chasenlz** [comment]
I figured it out, I was installing packages for python 2.7 and not 3 

For people that need help to install packages specifically for python3 use the command
 python3 -m pip install
@walmat

**Comment by walmat** [comment]
Glad you figured it out. 👍
