### ISSUE TITLE
Error code not sure how to fix

### ISSUE THREAD

**Issue by LMascher** [walmat/Off-White-Monitor#4]
C:\Users\Mascher\Off-White-Monitor>python main.py
[INFO] Off-White Monitor starting...
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    ow.__main__()
  File "C:\Users\Mascher\Off-White-Monitor\ow.py", line 295, in __main__
    with open('config.json') as config:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

Any help is amazing thanks for creating an amazing monitor

**Comment by Frezko** [comment]
You need to rename the config.sample.json to config.json then it should work.

**Comment by LMascher** [comment]
Frezko i did rename config.same.json to config.json any other ideas? Thanks tho

**Comment by Frezko** [comment]
Show me your Folder please.

**Comment by LMascher** [comment]
https://gyazo.com/71b6d0c8285624c044a7227794dbbf35
here u go frezko
(hey that rhymed)

**Comment by Frezko** [comment]
And Line 295 in ow.py please

**Comment by LMascher** [comment]
https://gyazo.com/dd0f7282fc1cccf096a6c5df079fe0c1
here is line 295 of ow.py, also do i need to change anything in line 309 for 'discord'?
https://gyazo.com/15f020deea72252001fc21855c29174a
i already put my webhook in config.json
btw in the photos it looks like its config.json.json i saw that and changed it and got same error

**Comment by walmat** [comment]
Show me the contents of your config.json. Make sure you blur out a part of your webhook url please. Need to check formatting of the file.

**Comment by LMascher** [comment]
https://gyazo.com/4cafba74caf4307a35762d902a561f04
config.json contents

**Comment by walmat** [comment]
Interesting. Message me on discord to help solve this faster. @walmat#5572 

@LMascher

**Comment by walmat** [comment]
Fixed over team viewer. Closing. If issue persists, feel free to open back up.
